import os

ALP = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'FinalCCNProject.alp')

def patch():
    with open(ALP, 'r', encoding='utf-8') as f:
        c = f.read()

    # Normalize to \n
    c = c.replace('\r\n', '\n')

    # ===== 1. NAME THE DATABASE OBJECT =====
    # This enables getDatabase() in Main
    if '<Database>' in c and '<Name>' not in c[c.find('<Database>'):c.find('</Database>')]:
        c = c.replace('<Database>', '<Database>\n\t\t<Name><![CDATA[database]]></Name>')

    # ===== 2. FIX COLORS IN TelemetryDash =====
    # Ensure all neon colors are defined
    color_defs = (
        '\t\tprivate java.awt.Color bgDark = new java.awt.Color(13, 17, 23);\n'
        '\t\tprivate java.awt.Color panelDark = new java.awt.Color(22, 27, 34);\n'
        '\t\tprivate java.awt.Color neonCyan = new java.awt.Color(0, 240, 255);\n'
        '\t\tprivate java.awt.Color neonMagenta = new java.awt.Color(255, 0, 255);\n'
        '\t\tprivate java.awt.Color neonGreen = new java.awt.Color(57, 255, 20);\n'
        '\t\tprivate java.awt.Color neonOrange = new java.awt.Color(255, 165, 0);\n'
        '\t\tprivate java.awt.Color neonRed = new java.awt.Color(255, 60, 60);'
    )
    
    # Find TelemetryDash color block and replace it
    import re
    c = re.sub(r'private java\.awt\.Color bgDark =.*?private java\.awt\.Color neonRed = new java\.awt\.Color\(255, 60, 60\);', color_defs, c, flags=re.DOTALL)

    # ===== 3. FIX ReportDash CONTEXT + COLORS + DB ACCESS =====
    
    # 3a. Update ReportDash class definition and add colors
    report_class_start = (
        'public class ReportDash extends javax.swing.JFrame {\n'
        '\t\tprivate final Main main;\n'
        '\t\tprivate java.util.ArrayList<String> logLines = new java.util.ArrayList<>();\n'
        '\t\tprivate int pktCount=0, anomCount=0, rlActions=0, ganInjections=0;\n'
        '\t\tprivate double sumError=0, minLat=Double.MAX_VALUE, maxLat=0, lastPred=0, lastActual=0;\n'
        '\t\tprivate long startMs = System.currentTimeMillis();\n'
        '\t\tprivate java.awt.Color bgDark=new java.awt.Color(13,17,23);\n'
        '\t\tprivate java.awt.Color panelDark=new java.awt.Color(22,27,34);\n'
        '\t\tprivate java.awt.Color neonCyan=new java.awt.Color(0,240,255);\n'
        '\t\tprivate java.awt.Color neonGreen=new java.awt.Color(57,255,20);\n'
        '\t\tprivate java.awt.Color neonOrange=new java.awt.Color(255,165,0);\n'
        '\t\tprivate java.awt.Color neonRed=new java.awt.Color(255,60,60);\n'
        '\t\tprivate java.awt.Color neonMagenta=new java.awt.Color(255,0,255);'
    )
    
    c = re.sub(r'public class ReportDash extends javax\.swing\.JFrame \{.*?private java\.awt\.Color neonOrange=new java\.awt\.Color\(255,165,0\);', report_class_start, c, flags=re.DOTALL)

    # 3b. Update Constructor
    if 'public ReportDash() {' in c:
        c = c.replace('public ReportDash() {', 'public ReportDash(Main main) {\n\t\t\tthis.main = main;')
    
    # 3c. Update DB Logging in addData
    # Use main.getDatabase().executeStatement
    db_insert_logic = (
        '\t\t\t\ttry {\n'
        '\t\t\t\t\tmain.getDatabase().executeStatement("INSERT INTO SIM_LOGS (LOG_TEXT) VALUES (\'" + lastLog.replace("\'", "\'\'") + "\')");\n'
        '\t\t\t\t} catch (Exception e) { }\n'
    )
    # Find where logLines.add is called and inject after it if not already there
    if 'main.getDatabase().executeStatement' not in c:
        c = c.replace(
            'logLines.add(String.format("[%05d] \\u2713 Processed lat=%.2f pred=%.3f err=%.4f",pktCount,actual,pred,Math.abs(actual-pred)));',
            'String entry = String.format("[%05d] \\u2713 Processed lat=%.2f pred=%.3f err=%.4f",pktCount,actual,pred,Math.abs(actual-pred));\n'
            '\t\t\t\tlogLines.add(entry);\n'
            '\t\t\t\ttry {\n'
            '\t\t\t\t\tmain.getDatabase().executeStatement("INSERT INTO SIM_LOGS (LOG_TEXT) VALUES (\'" + entry.replace("\'", "\'\'") + "\')");\n'
            '\t\t\t\t} catch (Exception e) { }'
        )

    # ===== 4. STARTUP CODE UPDATES =====
    c = c.replace('rptDash = new ReportDash();', 'rptDash = new ReportDash(this);')
    
    # Table creation using getDatabase()
    c = c.replace(
        'rptDash.setVisible(true);\n'
        '\t\ttry {\n'
        '\t\t\tgetEngine().getDatabaseManager().executeStatement("CREATE TABLE IF NOT EXISTS SIM_LOGS (AL_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, LOG_TEXT VARCHAR(1000), LOG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");\n'
        '\t\t} catch (Exception e) { e.printStackTrace(); }',
        
        'rptDash.setVisible(true);\n'
        '\t\ttry {\n'
        '\t\t\tgetDatabase().executeStatement("CREATE TABLE IF NOT EXISTS SIM_LOGS (AL_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, LOG_TEXT VARCHAR(1000), LOG_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");\n'
        '\t\t} catch (Exception e) { e.printStackTrace(); }'
    )

    # ===== 5. DASHBOARD 3 HUB DESIGN (Ensure colors match) =====
    hub_code = (
        'g2d.drawString("RL & GAN Synthesis Hub", 15, 30);\n'
        '\t\t\t\t\tg2d.setFont(new java.awt.Font("Consolas", java.awt.Font.ITALIC, 9));\n'
        '\t\t\t\t\tg2d.setColor(new java.awt.Color(120,120,120));\n'
        '\t\t\t\t\tg2d.drawString("Q-Learning + WGAN-GP + Federated FL", 15, 42);\n'
        '\n'
        '\t\t\t\t\t// 1. Q-LEARNING REWARD PROGRESS\n'
        '\t\t\t\t\tg2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));\n'
        '\t\t\t\t\tg2d.setColor(neonGreen);\n'
        '\t\t\t\t\tg2d.drawString("Agent Reward Stability", 15, 75);\n'
        '\t\t\t\t\tint barW = getWidth()-40;\n'
        '\t\t\t\t\tg2d.setColor(new java.awt.Color(40,40,50));\n'
        '\t\t\t\t\tg2d.fillRoundRect(15, 85, barW, 20, 10, 10);\n'
        '\t\t\t\t\tdouble rewardNorm = Math.min(1.0, (totalPackets % 100) / 100.0);\n'
        '\t\t\t\t\tg2d.setPaint(new java.awt.GradientPaint(15, 0, neonGreen, 15 + (int)(barW*rewardNorm), 0, new java.awt.Color(0,100,0)));\n'
        '\t\t\t\t\tg2d.fillRoundRect(15, 85, (int)(barW * rewardNorm), 20, 10, 10);\n'
        '\t\t\t\t\tg2d.setColor(java.awt.Color.WHITE);\n'
        '\t\t\t\t\tg2d.setFont(new java.awt.Font("Consolas", java.awt.Font.BOLD, 11));\n'
        '\t\t\t\t\tg2d.drawString(String.format("Current Policy: Optimizing (%.1f%%)", rewardNorm*100), 25, 99);\n'
        '\n'
        '\t\t\t\t\t// 2. GAN DDoS SYNTHESIS PULSE\n'
        '\t\t\t\t\tg2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));\n'
        '\t\t\t\t\tg2d.setColor(neonOrange);\n'
        '\t\t\t\t\tg2d.drawString("GAN Synthesis Pulse", 15, 135);\n'
        '\t\t\t\t\tfor(int i=0; i<8; i++) {\n'
        '\t\t\t\t\t\tint alpha = (int)(255 * Math.abs(Math.sin(System.currentTimeMillis()/500.0 - i*0.5)));\n'
        '\t\t\t\t\t\tg2d.setColor(new java.awt.Color(255, 165, 0, alpha));\n'
        '\t\t\t\t\t\tg2d.fillOval(20 + i*40, 145, 15, 15);\n'
        '\t\t\t\t\t}\n'
        '\t\t\t\t\tg2d.setColor(java.awt.Color.LIGHT_GRAY);\n'
        '\t\t\t\t\tg2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.ITALIC, 11));\n'
        '\t\t\t\t\tg2d.drawString("Simulating synthetic DDoS vectors via WGAN-GP...", 15, 175);\n'
        '\n'
        '\t\t\t\t\t// 3. FEDERATED LEARNING ROUNDS\n'
        '\t\t\t\t\tg2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));\n'
        '\t\t\t\t\tg2d.setColor(neonCyan);\n'
        '\t\t\t\t\tg2d.drawString("Federated Learning (Aggregation Round)", 15, 210);\n'
        '\t\t\t\t\tint round = (totalPackets / 200) + 1;\n'
        '\t\t\t\t\tg2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 36));\n'
        '\t\t\t\t\tg2d.drawString("#" + round, 15, 255);\n'
        '\t\t\t\t\tg2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));\n'
        '\t\t\t\t\tg2d.setColor(java.awt.Color.WHITE);\n'
        '\t\t\t\t\tg2d.drawString("Active Nodes: 12 Global Aggregators", 15, 275);\n'
        '\n'
        '\t\t\t\t\t// 4. REAL-TIME AI HEALTH\n'
        '\t\t\t\t\tg2d.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));\n'
        '\t\t\t\t\tg2d.setColor(neonMagenta);\n'
        '\t\t\t\t\tg2d.drawString("System Entropy", 15, 310);\n'
        '\t\t\t\t\tdouble entropy = 0.1 + (totalAnomalies % 10) / 20.0;\n'
        '\t\t\t\t\tg2d.setColor(new java.awt.Color(40,40,50));\n'
        '\t\t\t\t\tg2d.fillRect(15, 320, barW, 10);\n'
        '\t\t\t\t\tg2d.setColor(neonMagenta);\n'
        '\t\t\t\t\tg2d.fillRect(15, 320, (int)(barW * entropy), 10);'
    )
    # If the hub isn't already there, replace the KPI matrix or monitor
    if 'RL & GAN Synthesis Hub' not in c:
        c = re.sub(r'g2d\.drawString\("Live Telemetry KPI Matrix", 20, 40\);.*?g2d\.drawString\("GLOBAL MAE", 20, 315\);', hub_code, c, flags=re.DOTALL)

    with open(ALP, 'w', encoding='utf-8') as f:
        f.write(c)
    print("SUCCESS: Full V4 Ultra Patch applied. Database named, colors defined, and context fixed!")

if __name__ == '__main__':
    patch()
